# Generated by Django 4.0.4 on 2022-04-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_processor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='processor',
            name='model_of_processor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.prefix'),
        ),
    ]
