# Generated by Django 4.0.4 on 2022-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_processor_model_of_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
