# Generated by Django 4.0.4 on 2022-04-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_processor_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processor',
            old_name='model',
            new_name='modelee',
        ),
    ]
