# Generated by Django 4.0.4 on 2022-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_processor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='image',
        ),
    ]
