# Generated by Django 4.0.4 on 2022-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_processor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
