# Generated by Django 4.0.4 on 2022-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_micro_alter_processor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='processor',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Micro',
        ),
    ]
