# Generated by Django 4.0.4 on 2022-04-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_micro_alter_processor_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='image',
        ),
    ]
