# Generated by Django 4.0.4 on 2022-05-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
